project:
  type: book
  output-dir: docs

book:
  title: "DATA / STAT 334"
  reader-mode: true
  page-footer:
    left: |
      Course Materials were written by Matt Higham for STAT/DATA 334 at St. Lawrence University.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - part: Getting Started
      chapters:
      - 00-choose-viz.qmd
      - 01-concepts.qmd
      - 04-concepts-applied.qmd
      - 02-software.qmd
    - part: Visualization in R
      chapters:
      - 03-statdata234.qmd
      - 06-mapping.qmd
      - 05-uncertainty.qmd
      - 14-other-topics.qmd
    - part: Model Visualization
      chapters:
      - 07-stat213.qmd
      - 08-model-interactions.qmd
      - 09-logistic.qmd
      - 10-ethics.qmd
    - part: Interactive Visualization
      chapters:
      - 11-when-to-use.qmd
      - 12-shiny-intro.qmd
      - 13-shiny-reactivity.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - ds234.scss
    code-link: true
    callout-appearance: simple


