---
title: "Creating a Quarto Blog"
format:
  html:
    self-contained: true
---

The following site gives more detailed information about starting up a Quarto blog: <https://quarto.org/docs/websites/website-blog.html>.

#### Creating the Blog

To create a `Quarto` Blog in `R Studio`, go to `File -> New Project -> New Directory -> Quarto Blog`

Check the "Create a Git repository" checkbox, give the project a name (without spaces), and select a directory for the project to be created in.

Before moving on, make sure that you can Render the blog, by clicking the "Render Website" button in the "Build" tab in the upper-right window of `R Studio`.

#### Creating a New Post

To create a new post, first create a new Folder in within the "Posts" folder of your Project. Then, create a new Quarto `.qmd` file (HTML), type some code into the file, and save the file as `index.qmd` within your new folder.

Render the blog by again clicking the "Render Website" button in the "Build" tab to verify that your new post appears.

#### Unfreezing Output

By default, this post is now "Frozen." Changing code within a code chunk will not change the output. To change this behaviour, navigate to the "Posts" folder and click on the `_metadata.yml` file. In the file, change `freeze: true` to `freeze: false`, which will unfreeze the code in all of the posts in the "Posts" folder.

We will change this option back in the future, after we discuss the benefits of `freeze: true`. 

<br>


